const translations = {
  en: {
    // Common
    welcome: 'Welcome',
    welcomeTitle: 'Connecting Local',
    farmers: 'Farmers',
    consumers: 'Consumers',
    welcomeSubtitle: 'Direct farmer-to-consumer marketplace for fresh, local produce',
    getStarted: 'Get Started',
    continue: 'Continue',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    
    // Language Selection
    selectLanguage: 'Select Language',
    languageSaved: 'Language preference saved',
    
    // Role Selection
    selectYourRole: 'Select Your Role',
    roleSelectionDesc: 'Choose how you want to use Farm Bridge',
    farmer: 'Farmer',
    buyer: 'Buyer',
    farmerDesc: 'Sell your fresh produce directly to local consumers',
    buyerDesc: 'Buy fresh produce directly from local farmers',
    iAmFarmer: 'I am a Farmer',
    iAmBuyer: 'I am a Buyer',
    continueAs: 'Continue as {role}',
    selectRoleToContinue: 'Select a role to continue',
    roleSelectionNote: 'You can change your role later in settings',
    
    // Farmer
    farmerDashboard: 'Farmer Dashboard',
    myProducts: 'My Products',
    addNewProduct: 'Add New Product',
    manageYourProductListings: 'Manage your product listings',
    searchProducts: 'Search products...',
    all: 'All',
    noProductsFound: 'No products found',
    addYourFirstProduct: 'Add your first product to get started',
    addFirstProduct: 'Add First Product',
    active: 'Active',
    inactive: 'Inactive',
    edit: 'Edit',
    delete: 'Delete',
    confirmDeleteProduct: 'Are you sure you want to delete this product?',
    selectCategory: 'Select Category',
    productName: 'Product Name',
    enterProductName: 'Enter product name',
    description: 'Description',
    voiceInputAvailable: 'Voice input available',
    enterProductDescription: 'Enter product description',
    quantity: 'Quantity',
    pricePerUnit: 'Price per unit',
    availableQuantity: 'Available Quantity',
    harvestDate: 'Harvest Date',
    uploadImages: 'Upload Images',
    dragDropImages: 'Drag & drop images here, or click to browse',
    browseFiles: 'Browse Files',
    saveProduct: 'Save Product',
    pendingOrders: 'Pending Orders',
    activeProducts: 'Active Products',
    monthlyEarnings: 'Monthly Earnings',
    customerRating: 'Customer Rating',
    quickActions: 'Quick Actions',
    addProduct: 'Add Product',
    viewOrders: 'View Orders',
    viewAnalytics: 'View Analytics',
    messages: 'Messages',
    recentOrders: 'Recent Orders',
    viewAll: 'View All',
    noOrdersYet: 'No orders yet',
    
    // Buyer
    buyerDashboard: 'Buyer Dashboard',
    freshProduceNearYou: 'Fresh Produce Near You',
    searchFarmersProducts: 'Search farmers & products...',
    sortBy: 'Sort by',
    distance: 'Distance',
    price: 'Price',
    freshness: 'Freshness',
    rating: 'Rating',
    filters: 'Filters',
    organicOnly: 'Organic Only',
    availableToday: 'Available Today',
    farmerVerified: 'Farmer Verified',
    addToCart: 'Add to Cart',
    viewDetails: 'View Details',
    justHarvested: 'Just Harvested',
    veryFresh: 'Very Fresh',
    fresh: 'Fresh',
    moderate: 'Moderate',
    stock: 'Stock',
    per: 'per',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    contactFarmer: 'Contact Farmer',
    cart: 'Cart',
    checkout: 'Checkout',
    total: 'Total',
    placeOrder: 'Place Order',
    paymentMethods: 'Payment Methods',
    upi: 'UPI',
    cashOnDelivery: 'Cash on Delivery',
    bankTransfer: 'Bank Transfer',
    orderSummary: 'Order Summary',
    deliveryAddress: 'Delivery Address',
    changeAddress: 'Change Address',
    orderConfirmation: 'Order Confirmation',
    trackOrder: 'Track Order',
    rateProduct: 'Rate Product',
    
    // Maps & Tracking
    liveTracking: 'Live Tracking',
    orderTracking: 'Order Tracking',
    currentLocation: 'Current Location',
    estimatedDelivery: 'Estimated Delivery',
    deliveryProof: 'Delivery Proof',
    uploadProof: 'Upload Proof',
    trackingHistory: 'Tracking History',
    
    // Profile
    profile: 'Profile',
    editProfile: 'Edit Profile',
    name: 'Name',
    phone: 'Phone',
    email: 'Email',
    age: 'Age',
    place: 'Place',
    address: 'Address',
    pincode: 'Pincode',
    fullAddress: 'Full Address',
    bankDetails: 'Bank Details',
    bankAccountNumber: 'Bank Account Number',
    upiId: 'UPI ID',
    preferences: 'Preferences',
    productPreferences: 'Product Preferences',
    priceRange: 'Price Range',
    saveChanges: 'Save Changes',
    
    // Notifications
    notifications: 'Notifications',
    markAllAsRead: 'Mark all as read',
    newOrder: 'New Order',
    orderDelivered: 'Order Delivered',
    paymentReceived: 'Payment Received',
    newMessage: 'New Message',
    orderUpdate: 'Order Update',
    
    // Support
    helpSupport: 'Help & Support',
    faq: 'FAQ',
    contactUs: 'Contact Us',
    termsConditions: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    
    // Footer
    supportingLocalAgriculture: 'Supporting Local Agriculture',
    allRightsReserved: 'All rights reserved',
    
    // Stats
    farmersConnected: 'Farmers Connected',
    ordersDelivered: 'Orders Delivered',
    satisfactionRate: 'Satisfaction Rate',
    directFromFarm: 'Direct from Farm',
    directFromFarmDesc: 'Fresh produce directly from farmers',
    hyperlocal: 'Hyperlocal',
    hyperlocalDesc: 'Connect with farmers in your locality',
    fairPrices: 'Fair Prices',
    fairPricesDesc: 'Better prices for farmers, affordable for buyers',
    easyToUse: 'Easy to Use',
    easyToUseDesc: 'Simple interface for everyone',
  },
  
  hi: {
    welcome: 'स्वागत है',
    welcomeTitle: 'स्थानीय को जोड़ना',
    farmers: 'किसान',
    consumers: 'उपभोक्ता',
    welcomeSubtitle: 'ताजा, स्थानीय उपज के लिए सीधा किसान-से-उपभोक्ता बाज़ार',
    getStarted: 'शुरू करें',
    continue: 'जारी रखें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    
    farmer: 'किसान',
    buyer: 'खरीदार',
    farmerDesc: 'अपनी ताजा उपज सीधे स्थानीय उपभोक्ताओं को बेचें',
    buyerDesc: 'स्थानीय किसानों से सीधे ताजा उपज खरीदें',
    
    // Add more translations for all phrases
  },
  
  // Add translations for other languages similarly
  ta: {},
  te: {},
  kn: {},
  ml: {},
  bn: {},
  mr: {},
  gu: {},
  pa: {},
  or: {}
};

export default translations;